FROM python:3.7.2-alpine3.9
LABEL maintainer="Radoslav Sandov <rsandov@softserveinc.com>"

RUN apk add --no-cache gcc libc-dev postgresql-dev python3-dev musl-dev \
    && pip install poetry gunicorn

COPY ./docker/gunicorn_conf.py ./docker/entrypoint.sh /
RUN chmod +x /entrypoint.sh && mkdir -p /app
WORKDIR /app/

COPY ./backend/pyproject.toml ./backend/poetry.lock /app/

RUN poetry config settings.virtualenvs.create false && poetry install --no-dev

COPY ./backend/app /app/app

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
