FROM node:11.9-alpine as build-stage
LABEL maintainer="Eugene Yunak <yyunak@softserveinc.com>"

RUN apk add --no-cache --virtual make

WORKDIR /home/node

COPY ./frontend/package*.json ./frontend/Makefile ./
RUN make install

COPY ./frontend/ .
ARG API_ROOT
RUN make build

FROM nginx:mainline-alpine
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /home/node/build/ /usr/share/nginx/html
