jenkins:
  systemMessage: "Jenkins server for MAF project"
  remotingSecurity:
    enabled: true
  numExecutors: 1
  scmCheckoutRetryCount: 2
  mode: NORMAL
  quietPeriod: 5
  crumbIssuer: 
    standard:
       excludeClientIPFromCrumb: true

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  securityRealm:
    github:
      githubWebUri: "https://github.com"
      githubApiUri: "https://api.github.com"
      clientID: "bf828dadc2d4e6a19a9c"
      clientSecret: "54498a81ad4dd676c0ddca2b808e5b67afaad400"
      oauthScopes: "read:org,user:email,repo"
      
tool:
  git:
    installations:
      - home: "git"
        name: "Default"

jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/mykolaantonivmafpoc/poc.git' }
                        branch 'master'
                        extensions {}
                    }
                  }
              }
          }
      }