export const GETALL_REQUEST = 'CAMPAIGNS_GETALL_REQUEST';
export const GETALL_SUCCESS = 'CAMPAIGNS_GETALL_SUCCESS';
export const GETALL_FAILURE = 'CAMPAIGNS_GETALL_FAILURE';

export const GETONE_REQUEST = 'CAMPAIGNS_GETONE_REQUEST';
export const GETONE_SUCCESS = 'CAMPAIGNS_GETONE_SUCCESS';
export const GETONE_FAILURE = 'CAMPAIGNS_GETONE_FAILURE';
