export const GETOPTIONS_REQUEST = 'HATEOAS_GETOPTIONS_REQUEST';
export const GETOPTIONS_SUCCESS = 'HATEOAS_GETOPTIONS_SUCCESS';
export const GETOPTIONS_FAILURE = 'HATEOAS_GETOPTIONS_FAILURE';

export const LINKS = '_links';
